### ISSUE TITLE
About Sleep Issue

### ISSUE THREAD

**Issue by bilaleminturker06** [seven-of-eleven/SurfacePro7#1]
Hello.  When pc goes to sleep, it consumes to much battery. I guess ıt does not goes to sleep sleep

**Comment by seven-of-eleven** [comment]
Ya. I've noted the same issue. Fan keeps spinning. I haven't spent much time on it to troubleshoot. I don't think I will as it is a secondary computer for me and I'm just in the habit of shutting down the laptop when I'm done with it.
